from datetime import datetime as dt

"""
  if an app lost in any host this alert is triggered.
"""

body = """
      <body style="color: #003366;font-size: 13px;margin-left: 15px;">
          <p>
              <br/> Hi team,
              <br>
              <p style="color: IndianRed;font-size: 13px;">
              Application <b>"{appid}"</b> have been <b>LOST</b> at `{ctime}` on host <b> {host} </b>
              </p>
              <br>
              <table style=>
                <tr><td>timestamp </td> <td>: {timestamp}</td></tr>
                <tr><td>slaveId </td> <td>: {slaveId}</td></tr>
                <tr><td>host </td> <td> : {host}</td> </tr>
                <!-- COMMENTED <tr> <td>ports </td> <td> : {ports}</td> </tr>  -->
                <!-- COMMENTED <tr> <td>version </td>  <td> : {version}</td> </tr> -->
                <!-- COMMENTED <tr> <td>message </td>  <td>: {message}</td>  </tr> -->
              <table>

          <p style="color: #003366;font-size: 13px;margin-left: 13px;">
          Regards, </br>
          marthon-alert,FlyTxt
          </p>
        <span style="font-size: 9px;color: #A0A0A0;">
            This is an autogenerated mail; Please do not reply
        </span>
      </body>
    """

def getsubject(ev):
  """ param: event"""
  appid = ev.appId
  return (
          '_alert_{stime}:{appid}-LOST'
              .format(stime=dt.utcnow().strftime('%Y-%m-%dT%H:%M:%S UTC'),appid=appid)
          )

def getbody(ev):
  """ param: event"""
  ctime =  dt.utcnow().strftime('%c') + ' UTC'

  b = body.format(timestamp=str(ev.timestamp),taskStatus=ev.taskStatus, host=ev.host,
                          ports=str(ev.ports), version=ev.version, slaveId=ev.slaveId,message=str(ev.message),
                          appid=ev.appId,
                          ctime=ctime
                    )

  return b



if __name__ == '__main__':

    print body.format(timestamp="",taskStatus="", host="",
                            ports='', version='', slaveId='',message="",
                            appid='',
                            ctime='')
    class x:
        appId = "testap"
    print getsubject(x())